#!/usr/bin/env python3
"""Generate the app's static image map from the question packs.

    python3 tools/gen-app-image-map.py            # write it
    python3 tools/gen-app-image-map.py --check     # fail if it is out of date

Why this file has to exist. Germany's picture questions reference their artwork by string
(`"optionImages": ["img/q21-bild1.jpg", ...]`), and React Native cannot resolve that.
Metro bundles an image only when it sees a `require()` with a **literal** path at build
time - `require('./img/' + name)` throws, and the versioned Expo docs for SDK 57 only ever
document static paths. So every path a pack can ask for gets a real `require()` written out
here, and the app looks the string up in the map instead of building a path.

The failure this prevents is quiet: without it the pack is valid, the JSON loads, the
question renders, and the four option tiles are simply empty - which reads as a broken test
rather than a missing build step. So `--check` runs in CI-ish fashion and the map is
regenerated whenever content changes.

The map is keyed by `<country>/<pack-relative path>`, so two countries may both have an
`img/q1.jpg` without colliding.
"""

import argparse
import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CONTENT = os.path.join(ROOT, "apps/us-citizenship/content")
OUT = os.path.join(ROOT, "apps/us-citizenship/src/content/images.generated.ts")

HEADER = """/* GENERATED by tools/gen-app-image-map.py - do not edit.
 *
 * Metro only bundles an image it can see in a `require()` with a literal path, so every
 * picture a question pack can reference is written out here and looked up by its string.
 * A dynamic `require()` would throw at runtime; an unbundled image renders as an empty
 * tile, which looks like a broken question rather than a missing asset.
 *
 * Regenerate after any content change:  python3 tools/gen-app-image-map.py
 */

export type PackImage = number;

/** Keyed by `<country>/<path as the pack writes it>`, e.g. `de/img/q21-bild1.jpg`. */
export const PACK_IMAGES: Record<string, PackImage> = {
"""

FOOTER = """};

/** The artwork for a pack-relative path, or undefined when we ship no file for it. */
export function packImage(country: string, rel: string | undefined): PackImage | undefined {
  if (!rel) return undefined;
  return PACK_IMAGES[`${country}/${rel}`];
}
"""


def referenced_images():
    """Every (country, pack-relative path) a pack asks for, with the file that backs it."""
    found = {}
    missing = []
    for country in sorted(os.listdir(CONTENT)):
        cdir = os.path.join(CONTENT, country)
        if not os.path.isdir(cdir):
            continue
        for name in sorted(os.listdir(cdir)):
            if not name.endswith(".json"):
                continue
            try:
                with open(os.path.join(cdir, name), encoding="utf-8") as f:
                    pack = json.load(f)
            except (OSError, json.JSONDecodeError):
                continue
            if not isinstance(pack, dict):
                continue
            groups = []
            for key in ("categories", "stateCategories"):
                value = pack.get(key)
                if isinstance(value, list):
                    groups.extend(value)
            for cat in groups:
                if not isinstance(cat, dict):
                    continue
                for q in cat.get("questions") or []:
                    refs = []
                    if q.get("image"):
                        refs.append(q["image"])
                    if isinstance(q.get("optionImages"), list):
                        refs.extend(q["optionImages"])
                    for rel in refs:
                        if not isinstance(rel, str) or os.path.isabs(rel) or ".." in rel.split("/"):
                            missing.append((country, str(rel), "unsafe path"))
                            continue
                        if not os.path.isfile(os.path.join(cdir, rel)):
                            missing.append((country, rel, "file does not exist"))
                            continue
                        found[f"{country}/{rel}"] = f"../../content/{country}/{rel}"
    return found, missing


def render(found):
    lines = [HEADER]
    for key in sorted(found):
        lines.append(f"  {json.dumps(key)}: require({json.dumps(found[key])}),\n")
    lines.append(FOOTER)
    return "".join(lines)


def main(argv=None):
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="exit non-zero if the generated file is missing or stale")
    args = ap.parse_args(argv)

    found, missing = referenced_images()
    if missing:
        print("packs reference artwork that cannot be bundled:", file=sys.stderr)
        for country, rel, why in missing:
            print(f"  {country}/{rel}: {why}", file=sys.stderr)
        return 1

    text = render(found)
    current = None
    if os.path.isfile(OUT):
        with open(OUT, encoding="utf-8") as f:
            current = f.read()

    if args.check:
        if current != text:
            print(f"{os.path.relpath(OUT, ROOT)} is out of date - "
                  f"run: python3 tools/gen-app-image-map.py", file=sys.stderr)
            return 1
        print(f"image map is up to date ({len(found)} image(s))")
        return 0

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as f:
        f.write(text)
    by_country = {}
    for key in found:
        by_country[key.split("/", 1)[0]] = by_country.get(key.split("/", 1)[0], 0) + 1
    print(f"wrote {os.path.relpath(OUT, ROOT)}: {len(found)} image(s) "
          f"({', '.join(f'{k} {v}' for k, v in sorted(by_country.items()))})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
